name: Install JDK and start Minecraft server

on:
  workflow_dispatch:

jobs:
  start-minecraft-server:
    runs-on: ubuntu-latest
    steps:
      - name: Download JDK 17
        run: |
          wget https://download.java.net/java/17/jdk17/current/GPL/openjdk-17_linux-x64_bin.tar.gz
          tar -xzvf openjdk-17_linux-x64_bin.tar.gz
          sudo mv jdk-17 /usr/lib/jvm/
          echo "export PATH=\$PATH:/usr/lib/jvm/jdk-17/bin" >> ~/.bashrc
          source ~/.bashrc
      
      - name: Download Minecraft Server
        run: |
          wget https://launcher.mojang.com/v1/objects/bb2b6b1aefcd70dfd1892149ac3a215f6c636b07/server.jar
          echo "eula=true" > eula.txt
      
      - name: Start Minecraft Server
        run: java -Xmx1024M -Xms1024M -jar server.jar nogui

          
      - name: dir 2
        run: |
          dir
          
      - name: Ip
        run: |
          ifconfig

      - name: Prestart the server
        run: |
          java -Xmx1024M -Xms1024M -jar server.jar nogui

      - name: Set Minecraft EULA to true
        run: |
          sed -i 's/eula=false/eula=true/' eula.txt

      - name: Set server port to 80
        run: |
          sed -i 's/^server-port=.*/server-port=80/' server.properties

      - name: Start Minecraft server
        run: |
          java -Xmx1024M -Xms1024M -jar server.jar nogui
