name: Generate Passwords

on: [push]

jobs:
  generate-passwords:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Generate passwords
      run: python generate_passwords.py
      
    - name: Upload passwords artifact
      uses: actions/upload-artifact@v2
      with:
        name: passwords
        path: passwords.txt
