name: Run custom shell commands

on:
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      command: "/bin/bash"
    steps:
      - name: Run custom shell commands
        run: |
          echo "Enter your shell commands below (type 'exit' to end input):"
          while true; do
            read commands
            if [ "$commands" = "exit" ]; then
              break
            else
              eval $commands
            fi
          done
